version: 2
updates:
  # Enable version updates for poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "sebastianpfischer"
      - "Pog3k"
      - "sebclrsn"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "./ci/"
    schedule:
      interval: "monthly"
    reviewers:
      - "sebastianpfischer"
      - "Pog3k"
